language: php

before_install:
  - sudo apt-get install -y poppler-utils

php:
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit